### ISSUE TITLE
Version agnostic

### ISSUE THREAD

**Issue by drwasho** [richardschneider/OpenBazaar-cli#2]
For future upgrades it would be good if the file path could be version agnostic. Right now I have the `1.1.9` server installed, but the client is looking for the server folder with `1.1.8` in the file path.

**Comment by richardschneider** [comment]
Yes, I was worried about that.  Will there be only be one client installed on a host, or should I use `semvar` for the latest version.

**Comment by richardschneider** [comment]
Published fixes as 0.0.45.  Please update to the latest version and try again

    npm install -g OpenBazaar-cli
